version: '3.8'
services:
  db:
    image: postgres:15
    container_name: production_control_db
    environment:
      POSTGRES_DB: production_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"